In [ ]:
### Load packages
import pandas as pd
import numpy as np
from time import time

In [ ]:
# Load Dataset
df=pd.read_csv("/content/emotion.csv")

In [ ]:
# preview
df.head()

                                                Text  Emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
# shape
df.shape

(21459, 2)

In [ ]:
# datatypes
df.dtypes

Text       object
Emotion    object
dtype: object

In [ ]:
# value counts of emotions
df['Emotion'].value_counts()

happy       7029
sadness     6265
anger       2993
fear        2652
love        1641
surprise     879
Name: Emotion, dtype: int64

In [ ]:
# sentiment analysis
from textblob import TextBlob

In [ ]:
def get_sentiment(text):
  blob = TextBlob(text)
  sentiment = blob.sentiment.polarity
  if sentiment > 0:
    result = "Positive"
  elif sentiment < 0:
    result = "Negative"
  else:
    result = "Neutral"
  return result

In [ ]:
# test function
get_sentiment("Childrens love to eat chocolate")

'Positive'

In [ ]:
df['Sentiment'] = df['Text'].apply(get_sentiment)

In [ ]:
df.head()

                                                Text  Emotion Sentiment
0                            i didnt feel humiliated  sadness   Neutral
1  i can go from feeling so hopeless to so damned...  sadness   Neutral
2   im grabbing a minute to post i feel greedy wrong    anger  Negative
3  i am ever feeling nostalgic about the fireplac...     love  Negative
4                               i am feeling grouchy    anger   Neutral

In [ ]:
# compare our emotion vs sentiment
df.groupby(['Emotion','Sentiment']).size()

Emotion   Sentiment
anger     Negative     1390
          Neutral       806
          Positive      797
fear      Negative     1153
          Neutral       665
          Positive      834
happy     Negative      781
          Neutral      1035
          Positive     5213
love      Negative      318
          Neutral       234
          Positive     1089
sadness   Negative     2934
          Neutral      1592
          Positive     1739
surprise  Negative      329
          Neutral       152
          Positive      398
dtype: int64

In [ ]:
# list of emotions
emotion_list = df['Emotion'].unique().tolist()

In [ ]:
emotion_list

['sadness', 'anger', 'love', 'surprise', 'fear', 'happy']

In [ ]:
df[df['Emotion'] == 'joy']

Empty DataFrame
Columns: [Text, Emotion, Sentiment]
Index: []

In [ ]:
df[df['Emotion'] == 'sadness']

                                                    Text  Emotion Sentiment
0                                i didnt feel humiliated  sadness   Neutral
1      i can go from feeling so hopeless to so damned...  sadness   Neutral
5      ive been feeling a little burdened lately wasn...  sadness  Positive
10     i feel like i have to make the suffering i m s...  sadness  Negative
13                    i feel low energy i m just thirsty  sadness   Neutral
...                                                  ...      ...       ...
20731  The tears came , and rapidly dissolved her ang...  sadness  Negative
20732  Through a swell of tears Ruth stared incredulo...  sadness   Neutral
20733         She glanced down at the linoleum in despai  sadness  Negative
20734  Perhaps it was despair that made me believe th...  sadness   Neutral
20735             That he forgot his guest in his despai  sadness   Neutral

[6265 rows x 3 columns]

In [ ]:
df[df['Emotion'] == 'anger']

                                                    Text Emotion Sentiment
2       im grabbing a minute to post i feel greedy wrong   anger  Negative
4                                   i am feeling grouchy   anger   Neutral
12     i think it s the easiest time of year to feel ...   anger   Neutral
20     i feel irritated and rejected without anyone d...   anger   Neutral
24     i already feel like i fucked up though because...   anger  Negative
...                                                  ...     ...       ...
21175                         Irina hung up in exasperat   anger   Neutral
21176  She was acting like some idiotic schoolgirl , ...   anger  Positive
21177                 Jean-Paul gave a sigh of exasperat   anger   Neutral
21178                       Parkin sighed with exasperat   anger   Neutral
21179  With a small sigh of exasperation she thrust h...   anger  Negative

[2993 rows x 3 columns]

In [ ]:
df[df['Emotion'] == 'fear']

                                                    Text Emotion Sentiment
7      i feel as confused about life as a teenager or...    fear  Negative
19     i now feel compromised and skeptical of the va...    fear  Negative
21     i am feeling completely overwhelmed i have two...    fear  Positive
31     i remember feeling acutely distressed for a fe...    fear  Positive
53     i was stymied a little bit as i wrote feeling ...    fear  Negative
...                                                  ...     ...       ...
21454               Melissa stared at her friend in dism    fear   Neutral
21455  Successive state elections have seen the gover...    fear   Neutral
21456               Vincent was irritated but not dismay    fear   Neutral
21457  Kendall-Hume turned back to face the dismayed ...    fear   Neutral
21458                    I am dismayed , but not surpris    fear   Neutral

[2652 rows x 3 columns]

In [ ]:
df[df['Emotion'] == 'surprise']

                                                    Text   Emotion Sentiment
6      ive been taking or milligrams or times recomme...  surprise  Positive
32     i have seen heard and read over the past coupl...  surprise  Positive
57     i keep feeling pleasantly surprised at his sup...  surprise  Positive
64     i am now nearly finished the week detox and i ...  surprise  Positive
129    i too feel as if i am a stranger in a strange ...  surprise  Negative
...                                                  ...       ...       ...
20891  If the birds are disturbed during the process ...  surprise  Positive
20892  It was Blackberry who bullied the stupefied Pi...  surprise  Negative
20893  He woke stupefied , flicking his tongue over h...  surprise   Neutral
20894           Laura stared up at Ross in stupefied ama  surprise   Neutral
20895  The pain had faded into the background and she...  surprise   Neutral

[879 rows x 3 columns]

In [ ]:
start_time = time()

from nltk.tokenize import TweetTokenizer
# The reduce_len parameter will allow a maximum of 3 consecutive repeating characters, while trimming the rest
# For example, it will tranform the word: 'Helloooooooooo' to: 'Hellooo'
tk = TweetTokenizer(reduce_len=True)

data = []

# Separating our features (text) and our labels into two lists to smoothen our work
X = df['Emotion'].tolist()
Y = df['Text'].tolist()

# Building our data list, that is a list of tuples, where each tuple is a pair of the tokenized text
# and its corresponding label
for x, y in zip(X, Y):
    if y == 4:
        data.append((tk.tokenize(x), 1))
    else:
        data.append((tk.tokenize(x), 0))

  # Printing the CPU time and the first 5 elements of our 'data' list
print('CPU Time:', time() - start_time)
data[:5]

CPU Time: 0.25133681297302246

[(['sadness'], 0),
 (['sadness'], 0),
 (['anger'], 0),
 (['love'], 0),
 (['anger'], 0)]

In [ ]:
from nltk.tag import pos_tag
from nltk.stem.wordnet import WordNetLemmatizer

In [ ]:
import re, string

def cleaned(token):
    if token == 'u':
        return 'you'
    if token == 'r':
        return 'are'
    if token == 'some1':
      return 'someone'
    if token == 'yrs':
        return 'years'
    if token == 'hrs':
        return 'hours'
    if token == 'mins':
        return 'minutes'
    if token == 'secs':
        return 'seconds'
    if token == 'pls' or token == 'plz':
        return 'please'
    if token == '2morow':
        return 'tomorrow'
    if token == '2day':
        return 'today'
    if token == '4got' or token == '4gotten':
        return 'forget'
    if token == 'amp' or token == 'quot' or token == 'lt' or token == 'gt' or token == '½25':
        return ''
    return token

Compare with SparkNLP

In [ ]:
# load packages
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

In [ ]:
# vectorizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [ ]:
# metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,plot_confusion_matrix

In [ ]:
# split our dataset
from sklearn.model_selection import train_test_split

In [ ]:
## bulid features for our text

In [ ]:
Afeatures = df['Text']
blabels = df['Emotion']

In [ ]:
Afeatures

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
21454                 Melissa stared at her friend in dism
21455    Successive state elections have seen the gover...
21456                 Vincent was irritated but not dismay
21457    Kendall-Hume turned back to face the dismayed ...
21458                      I am dismayed , but not surpris
Name: Text, Length: 21459, dtype: object

In [ ]:
blabels

0        sadness
1        sadness
2          anger
3           love
4          anger
          ...
21454       fear
21455       fear
21456       fear
21457       fear
21458       fear
Name: Emotion, Length: 21459, dtype: object

In [ ]:
# vectorizer
cv = CountVectorizer()
a = cv.fit_transform(Afeatures)

In [ ]:
# get features by name
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '15',
 '18',
 '1878',
 '19',
 '1915',
 '1917',
 '1926',
 '1929',
 '1974',
 '1975',
 '1978',
 '1980',
 '1980s',
 '1984',
 '1986',
 '1987',
 '1989',
 '1991',
 '1992',
 '1993',
 '1997',
 '19th',
 '200',
 '20th',
 '21',
 '23',
 '23r',
 '24',
 '30',
 '32',
 '33',
 '34',
 '37574',
 '40',
 '40th',
 '46',
 '48',
 '50',
 '500',
 '55',
 '70',
 '75th',
 '82nd',
 '94',
 '95',
 '9th',
 'aa',
 'aaaaaaand',
 'aaaaand',
 'aaaah',
 'aaaand',
 'aac',
 'aahhh',
 'aaron',
 'ab',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abated',
 'abba',
 'abbigail',
 'abc',
 'abd',
 'abdomen',
 'abdominal',
 'abducted',
 'abelard',
 'abhorrent',
 'abide',
 'abigail',
 'abilities',
 'ability',
 'abit',
 'abjectly',
 'able',
 'ableness',
 'ablo',
 'abnormally',
 'aboard',
 'abolitionists',
 'abominable',
 'abortion',
 'abou',
 'abound',
 'about',
 'above',
 'abraham',
 'abroad',
 'abruptly',
 'absence',
 'absoloutely',
 'absolute',
 'absolutely',
 'absolutly',
 'absorbed',
 'absorption',
 'abstain',
 'abstinence',
 'abstract',
 'absurd',
 'absurdity',
 'absurdly',
 'abt',
 'abu',
 'abundance',
 'abundantly',
 'abus',
 'abuse',
 'abused',
 'abuses',
 'abusing',
 'abusive',
 'abyss',
 'ac',
 'academia',
 'academic',
 'academics',
 'academy',
 'acause',
 'accelerated',
 'accent',
 'accentuating',
 'accept',
 'acceptable',
 'acceptance',
 'acceptances',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessaries',
 'accessibility',
 'accessible',
 'accessories',
 'accessory',
 'accident',
 'accidentally',
 'accidents',
 'acclimated',
 'acco',
 'accommodate',
 'accommodation',
 'accompanied',
 'accompaniment',
 'accompany',
 'accomplish',
 'accomplished',
 'accomplishing',
 'accomplishment',
 'accomplishments',
 'accord',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accountants',
 'accounted',
 'accounts',
 'accrue',
 'acctually',
 'accumulate',
 'accumulated',
 'accumulation',
 'accurate',
 'accurately',
 'accusation',
 'accused',
 'accuser',
 'accuses',
 'accusing',
 'accustomed',
 'ace',
 'ache',
 'ached',
 'acheivment',
 'aches',
 'achieve',
 'achieved',
 'achievement',
 'achievements',
 'achieving',
 'aching',
 'achy',
 'acid',
 'acim',
 'acker',
 'acknowledge',
 'acknowledged',
 'acknowledgement',
 'acknowledgment',
 'acne',
 'aconfident',
 'acquaint',
 'acquaintances',
 'acquainted',
 'acquire',
 'acquired',
 'acquit',
 'acronym',
 'across',
 'act',
 'actauly',
 'acted',
 'acting',
 'action',
 'actions',
 'activations',
 'active',
 'actively',
 'activism',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'actresses',
 'acts',
 'actual',
 'actuality',
 'actually',
 'acuity',
 'acumen',
 'acute',
 'acutely',
 'ad',
 'adam',
 'adams',
 'adapt',
 'adapted',
 'adaption',
 'add',
 'added',
 'addict',
 'addicted',
 'addiction',
 'addictive',
 'adding',
 'addison',
 'addisons',
 'addition',
 'additional',
 'additionally',
 'addled',
 'address',
 'addressed',
 'addressing',
 'adds',
 'ade',
 'adequate',
 'adequately',
 'adf',
 'adhere',
 'adherence',
 'adjectival',
 'adjectives',
 'adjoining',
 'adjust',
 'adjusting',
 'adjustment',
 'adjustments',
 'admin',
 'administration',
 'administrator',
 'administrators',
 'admiral',
 'admiration',
 'admire',
 'admired',
 'admires',
 'admiring',
 'admission',
 'admissions',
 'admit',
 'admits',
 'admittance',
 'admitted',
 'admittedly',
 'admitting',
 'adn',
 'adolescence',
 'adomen',
 'adopt',
 'adopted',
 'adopting',
 'adoption',
 'adorable',
 'adoration',
 'adore',
 'adored',
 'adores',
 'adoring',
 'adorns',
 'adrasteius',
 'adrenaline',
 'adress',
 'adrian',
 'adrift',
 'ads',
 'adsense',
 'adult',
 'adulth',
 'adulthood',
 'adults',
 'advance',
 'advanced',
 'advancement',
 'advances',
 'advantage',
 'advent',
 'adventure',
 'adventures',
 'adventurous',
 'adversary',
 'adverse',
 'adversely',
 'advertised',
 'advertisement',
 'advertisements',
 'advertises',
 'advertising',
 'advertorial',
 'adverts',
 'advice',
 'advil',
 'advise',
 'advisers',
 'advocacy',
 'advocate',
 'advocates',
 'advocating',
 'aesthetic',
 'aesthetics',
 'af',
 'afaerytaleinmakebelieve',
 'afar',
 'aff',
 'affair',
 'affairs',
 'affeccion',
 'affect',
 'affected',
 'affecti',
 'affecting',
 'affection',
 'affectionate',
 'affectionately',
 'affections',
 'affects',
 'affend',
 'affiliate',
 'affirm',
 'affirmation',
 'affirmations',
 'affirmative',
 'affirmed',
 'afford',
 'affordable',
 'affords',
 'affron',
 'affronted',
 'afghan',
 'aficionado',
 'afield',
 'aforementioned',
 'afp',
 'afrad',
 'afrade',
 'afraid',
 'africa',
 'african',
 'africans',
 'after',
 'aftereffects',
 'aftermath',
 'afternoon',
 'afternoons',
 'afterward',
 'afterwards',
 'ag',
 'aga',
 'agai',
 'again',
 'against',
 'agape',
 'age',
 'aged',
 'ageing',
 'agencies',
 'agenda',
 'agent',
 'ages',
 'aggie',
 'aggrandisement',
 'aggravated',
 'aggravating',
 'aggression',
 'aggressive',
 'aggressiven',
 'agi',
 'agiatated',
 'agility',
 'aging',
 'agitat',
 'agitated',
 'agn',
 'agnes',
 'agnostics',
 'ago',
 'agonised',
 'agonising',
 'agonized',
 'agony',
 'agoraphobic',
 'agree',
 'agreed',
 'agreeing',
 'agreement',
 'agtalk',
 'ah',
 'ahaha',
 'ahahahaha',
 'ahead',
 'ahem',
 'ahhh',
 'ahkman',
 'ahmed',
 'ai',
 'aid',
 'aided',
 'aids',
 'aiiiiighhhht',
 'ailments',
 'aim',
 'aimed',
 'aiming',
 'aimless',
 'aimlessly',
 'aims',
 'ain',
 'aint',
 'air',
 'airbrushing',
 'airbus',
 'aircleaner',
 'aircraft',
 'airlin',
 'airline',
 'airplane',
 'airport',
 'airports',
 'airritated',
 'airtime',
 'aisl',
 'aisles',
 'aiw',
 'aj',
 'ajahn',
 'ajmed',
 'aka',
 'akin',
 'akron',
 'akshay',
 'aku',
 'akward',
 'al',
 'ala',
 'alabama',
 'alain',
 'alan',
 'alarm',
 'alarmed',
 'alarming',
 'alaska',
 'alba',
 'albeit',
 'albert',
 'albino',
 'album',
 'albums',
 'albuquerque',
 'alcest',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alcove',
 'ald',
 'aldridge',
 'alec',
 'alene',
 'alert',
 'alertness',
 'alex',
 'alexa',
 'alexander',
 'alexandra',
 'alexei',
 'alexis',
 'alfed',
 'alfie',
 'alfred',
 'algebra',
 'algorithmic',
 'alhamdulillah',
 'ali',
 'alibi',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alight',
 'align',
 'aligncenter',
 'alignment',
 'alise',
 'alittle',
 'alive',
 'all',
 'allah',
 'allan',
 'allegation',
 'alleging',
 'allen',
 'allergen',
 'allergic',
 'allergies',
 'allergy',
 'alleviate',
 'alley',
 'alleys',
 'alli',
 'alliance',
 'allies',
 'alll',
 'allocated',
 'allotted',
 'allow',
 'allowable',
 'allowances',
 'allowed',
 'allowfullscreen',
 'allowing',
 'allows',
 'alls',
 'allthingsbucks',
 'allusion',
 'ally',
 'almond',
 'almost',
 'aloft',
 'alon',
 'alone',
 'along',
 'alonger',
 'alongside',
 'aloof',
 'alot',
 'alotta',
 'alphabet',
 'alre',
 'already',
 'alright',
 'also',
 'alsways',
 'alt',
 'altar',
 'alteration',
 'alterations',
 'altered',
 'altering',
 'alternate',
 'alternated',
 'alternating',
 'alternative',
 'alternatives',
 'although',
 'altitudes',
 'altogether',
 'alton',
 'aluminum',
 'alumninium',
 'alva',
 'alway',
 'always',
 'am',
 'ama',
 'amalgamation',
 'amateurs',
 'amazed',
 'amazement',
 'amazing',
 'amazingly',
 'amazingness',
 'amazon',
 'ambassador',
 'amber',
 'ambience',
 'ambient',
 'ambition',
 'ambitious',
 'ambleside',
 'ambulance',
 'ambulatory',
 'ambushed',
 'amd',
 'amendment',
 'amenities',
 'america',
 'american',
 'americana',
 'americans',
 'americas',
 'amid',
 'amidst',
 'amish',
 'amisha',
 'amiss',
 'amits',
 'amkris',
 'amma',
 'amman',
 'among',
 'amongst',
 'amorous',
 'amorphous',
 'amos',
 'amount',
 'amounting',
 'amounts',
 'amp',
 'amparo',
 'ampatuan',
 'amped',
 'amphetamine',
 'ample',
 'amplified',
 'amplifies',
 'amsterdam',
 'amud',
 'amus',
 'amused',
 'amusem',
 'amusement',
 'amusing',
 'amvassago',
 'amy',
 'an',
 'ana',
 'anaestheti',
 'anaesthetic',
 'anal',
 'analogy',
 'analyse',
 'analyses',
 'analysing',
 'analysis',
 'analyze',
 'analyzed',
 'analyzing',
 'anansi',
 'anatomy',
 'ancestral',
 'anchorage',
 'ancient',
 'ancients',
 'and',
 'andangry',
 'andare',
 'anderson',
 'andintrupte',
 'andover',
 'andrea',
 'andreas',
 'andrew',
 'andri',
 'andrus',
 'andthenwear',
 'andy',
 'anesthetized',
 'ang',
 'angalo',
 'angee',
 'angel',
 'angeles',
 'angelic',
 'angels',
 'anger',
 'angered',
 'angie',
 'angle',
 'angled',
 'angles',
 'angry',
 'angst',
 'angsty',
 'anguis',
 'anguish',
 'anguished',
 'anha',
 'anim',
 'animal',
 'animals',
 'animate',
 'animated',
 'animators',
 'anime',
 'animesh',
 'animosity',
 'anipike',
 'ankle',
 'ankles',
 'anklets',
 'ann',
 'anna',
 'annabel',
 'anne',
 'annie',
 'anniversary',
 'annotating',
 'annotation',
 'announce',
 'announced',
 'announcement',
 'announcements',
 'announcing',
 'annoy',
 'annoya',
 'annoyance',
 'annoyed',
 'annoying',
 'annoyingly',
 'annual',
 'annuals',
 'annulled',
 'annulment',
 'annus',
 'ano',
 'anon',
 'anonymity',
 'anonymous',
 'anotehr',
 'another',
 'anothers',
 'ansi',
 'answer',
 'answered',
 'answering',
 'answers',
 'antagonism',
 'anthem',
 'anthology',
 'anthony',
 'anti',
 'anticipated',
 'anticipating',
 'anticipation',
 'antics',
 'antidepressants',
 'antidote',
 'antipasti',
 'antique',
 'antiquities',
 'antisocial',
 'antivirus',
 'antm',
 'antoinette',
 'antonio',
 'antonios',
 'ants',
 'antsy',
 'anxieties',
 'anxiety',
 'anxio',
 'anxious',
 'anxiously',
 'any',
 'anybody',
 'anyhow',
 'anymmore',
 'anymore',
 'anyone',
 'anyones',
 'anything',
 'anythings',
 'anyway',
 'anyways',
 'anywhere',
 'aoa',
 'aoi',
 'aol',
 'aoshi',
 'aout',
 'ap',
 'apa',
 'apart',
 'apartment',
 'apartments',
 'apathetic',
 'apathy',
 'apawa',
 'apaya',
 'apc',
 'apendages',
 'apgujeong',
 'aplin',
 'apo',
 'apocalypses',
 'apologetic',
 'apologies',
 'apologise',
 'apologize',
 'apologizes',
 'apologizing',
 'apology',
 'apoplectic',
 'apostrophe',
 'apothecaries',
 'apothecary',
 'app',
 'appalled',
 'apparent',
 'apparently',
 'appeal',
 'appealing',
 'appeals',
 'appear',
 'appearanc',
 'appearance',
 'appearances',
 'appeared',
 'appearing',
 'appears',
 'appease',
 'appeased',
 'appetite',
 'applainces',
 'applause',
 'apple',
 'applebees',
 'apples',
 'application',
 'applications',
 'applied',
 'apply',
 'applying',
 'appointed',
 'appointment',
 'appointments',
 'apprecia',
 'appreciate',
 'appreciated',
 'appreciates',
 'appreciation',
 'appreciative',
 'apprehension',
 'apprehensive',
 'appriciation',
 'apprised',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'appropriate',
 'appropriately',
 'approval',
 'approve',
 'approx',
 'approximate',
 'approximately',
 'apps',
 'appts',
 'apraxia',
 'april',
 'apron',
 'apt',
 'ar',
 'arab',
 'arabia',
 'arabs',
 'araminta',
 'arc',
 'arca',
 'arcade',
 'archbishop',
 'archdiocese',
 'arched',
 'archeological',
 'arches',
 'architects',
 'architectural',
 'architecturally',
 'ardmore',
 'are',
 'area',
 'areas',
 'aren',
 'arena',
 'arent',
 'aretha',
 'arguably',
 'argue',
 'argued',
 'arguing',
 'argume',
 'argument',
 'arguments',
 'ari',
 'arialblue',
 'ariel',
 'arise',
 'arist',
 'aristophanes',
 'arlovski',
 'arm',
 'armani',
 'armed',
 'armenian',
 'armistice',
 'armor',
 'armoury',
 'armpits',
 'arms',
 'army',
 'arnold',
 'aroma',
 'arose',
 'arou',
 'around',
 'arouse',
 'aroused',
 'arousing',
 'arrange',
 'arranged',
 'arrangement',
 'arrangements',
 'arrangment',
 'array',
 'arrested',
 'arrises',
 'arriva',
 'arrival',
 'arrivals',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogance',
 'arrogant',
 'arrow',
 'ars',
 'arse',
 'arsenal',
 'art',
 'artefacts',
 'article',
 'articles',
 'articulacy',
 'articulate',
 'articulated',
 'articulating',
 'artifically',
 'artificial',
 'artificially',
 'artillery',
 'artisan',
 'artisans',
 'artist',
 'artistic',
 'artistry',
 'artists',
 'arts',
 'artwork',
 'arty',
 'arugh',
 'arun',
 'arvo',
 'aryans',
 'aryiku',
 'as',
 'asa',
 'asami',
 'asasoulawakens',
 'asbestos',
 'ascension',
 'asciatic',
 'asd',
 'ash',
 'ashame',
 'ashamed',
 'ashers',
 'ashes',
 'ashi',
 'ashley',
 'ashlotte',
 ...]

In [ ]:
# split dataset
a_train,a_test,b_train,b_test = train_test_split(a,blabels,test_size=0.3,random_state=42)

Bulid our model

In [ ]:
nv_model = MultinomialNB()
nv_model.fit(a_train,b_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
# accuracy
nv_model.score(a_test,b_test)

0.7298850574712644

In [ ]:
# predictions
b_pred_for_nv = nv_model.predict(a_test)

In [ ]:
b_pred_for_nv

array(['happy', 'anger', 'happy', ..., 'happy', 'happy', 'happy'],
      dtype='<U8')

Make a single prediction
   - Vectorized our text
   - Applied our model

In [ ]:
sample_text = ["Childrens love to eat chocolates"]

In [ ]:
vect = cv.transform(sample_text).toarray()

In [ ]:
# make prediction
nv_model.predict(vect)

array(['anger'], dtype='<U8')

In [ ]:
# check for the prediction probability
nv_model.predict_proba(vect)

array([[0.41613346, 0.11519273, 0.16583231, 0.13849164, 0.15880846,
        0.0055414 ]])

In [ ]:
# get all class for our mdel
nv_model.classes_

array(['anger', 'fear', 'happy', 'love', 'sadness', 'surprise'],
      dtype='<U8')

In [ ]:
np.max(nv_model.predict_proba(vect))

0.41613346197705287

In [ ]:
def predict_emotion(sample_text,model):
  myvect = cv.transform(sample_text).toarray()
  prediction = model.predict(myvect)
  pred_proba = model.predict_proba(myvect)
  pred_percentage_for_all = dict(zip(model.classes_,pred_proba[0]))
  print("Prediction:{}, Prediction Score:{}".format(prediction[0],np.max(pred_proba)))
  return pred_percentage_for_all

In [ ]:
predict_emotion(sample_text,nv_model)

Prediction:anger, Prediction Score:0.41613346197705287

{'anger': 0.41613346197705287,
 'fear': 0.11519273031506465,
 'happy': 0.16583230534471807,
 'love': 0.138491636301465,
 'sadness': 0.15880846443901775,
 'surprise': 0.005541401622678697}

In [ ]:
predict_emotion(["He hates running all the day"],nv_model)

Prediction:sadness, Prediction Score:0.5341179399831655

{'anger': 0.05588534819550118,
 'fear': 0.050675626619212655,
 'happy': 0.3308094669723952,
 'love': 0.02699140135754462,
 'sadness': 0.5341179399831655,
 'surprise': 0.0015202168721778627}

Model Evaluation

In [ ]:
# classification
print(classification_report(b_test,b_pred_for_nv))

              precision    recall  f1-score   support

       anger       0.91      0.52      0.67       909
        fear       0.83      0.47      0.60       796
       happy       0.68      0.95      0.79      2059
        love       0.84      0.20      0.32       492
     sadness       0.72      0.92      0.81      1929
    surprise       0.80      0.08      0.14       253

    accuracy                           0.73      6438
   macro avg       0.80      0.52      0.55      6438
weighted avg       0.76      0.73      0.69      6438

In [ ]:
# confusion
confusion_matrix(b_test,b_pred_for_nv)

array([[ 477,   24,  176,    1,  230,    1],
       [  18,  371,  192,    2,  211,    2],
       [  11,    7, 1953,   10,   78,    0],
       [   3,    1,  303,   96,   89,    0],
       [  10,   15,  117,    3, 1782,    2],
       [   6,   31,  121,    2,   73,   20]])

Save Model

In [ ]:
import joblib

In [ ]:
model_file = open("emotion_classifier_lr_03_june_2021.pkl","wb")
joblib.dump(nv_model,model_file)
model_file.close

In [ ]:
# logisticRegression
lr_model = LogisticRegression()
lr_model.fit(a_train,b_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# accurancy
lr_model.score(a_test,b_test)

0.8895619757688723

In [ ]:
# single predict
predict_emotion(sample_text,lr_model)

Prediction:happy, Prediction Score:0.25933774641985785

{'anger': 0.23976571494731183,
 'fear': 0.1831847989566513,
 'happy': 0.25933774641985785,
 'love': 0.04136272560612473,
 'sadness': 0.24400795398550099,
 'surprise': 0.03234106008455336}

In [ ]:
 blabels.unique().tolist()

['sadness', 'anger', 'love', 'surprise', 'fear', 'happy']

In [ ]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '15',
 '18',
 '1878',
 '19',
 '1915',
 '1917',
 '1926',
 '1929',
 '1974',
 '1975',
 '1978',
 '1980',
 '1980s',
 '1984',
 '1986',
 '1987',
 '1989',
 '1991',
 '1992',
 '1993',
 '1997',
 '19th',
 '200',
 '20th',
 '21',
 '23',
 '23r',
 '24',
 '30',
 '32',
 '33',
 '34',
 '37574',
 '40',
 '40th',
 '46',
 '48',
 '50',
 '500',
 '55',
 '70',
 '75th',
 '82nd',
 '94',
 '95',
 '9th',
 'aa',
 'aaaaaaand',
 'aaaaand',
 'aaaah',
 'aaaand',
 'aac',
 'aahhh',
 'aaron',
 'ab',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abated',
 'abba',
 'abbigail',
 'abc',
 'abd',
 'abdomen',
 'abdominal',
 'abducted',
 'abelard',
 'abhorrent',
 'abide',
 'abigail',
 'abilities',
 'ability',
 'abit',
 'abjectly',
 'able',
 'ableness',
 'ablo',
 'abnormally',
 'aboard',
 'abolitionists',
 'abominable',
 'abortion',
 'abou',
 'abound',
 'about',
 'above',
 'abraham',
 'abroad',
 'abruptly',
 'absence',
 'absoloutely',
 'absolute',
 'absolutely',
 'absolutly',
 'absorbed',
 'absorption',
 'abstain',
 'abstinence',
 'abstract',
 'absurd',
 'absurdity',
 'absurdly',
 'abt',
 'abu',
 'abundance',
 'abundantly',
 'abus',
 'abuse',
 'abused',
 'abuses',
 'abusing',
 'abusive',
 'abyss',
 'ac',
 'academia',
 'academic',
 'academics',
 'academy',
 'acause',
 'accelerated',
 'accent',
 'accentuating',
 'accept',
 'acceptable',
 'acceptance',
 'acceptances',
 'accepted',
 'accepting',
 'accepts',
 'access',
 'accessaries',
 'accessibility',
 'accessible',
 'accessories',
 'accessory',
 'accident',
 'accidentally',
 'accidents',
 'acclimated',
 'acco',
 'accommodate',
 'accommodation',
 'accompanied',
 'accompaniment',
 'accompany',
 'accomplish',
 'accomplished',
 'accomplishing',
 'accomplishment',
 'accomplishments',
 'accord',
 'accordance',
 'according',
 'accordingly',
 'account',
 'accountants',
 'accounted',
 'accounts',
 'accrue',
 'acctually',
 'accumulate',
 'accumulated',
 'accumulation',
 'accurate',
 'accurately',
 'accusation',
 'accused',
 'accuser',
 'accuses',
 'accusing',
 'accustomed',
 'ace',
 'ache',
 'ached',
 'acheivment',
 'aches',
 'achieve',
 'achieved',
 'achievement',
 'achievements',
 'achieving',
 'aching',
 'achy',
 'acid',
 'acim',
 'acker',
 'acknowledge',
 'acknowledged',
 'acknowledgement',
 'acknowledgment',
 'acne',
 'aconfident',
 'acquaint',
 'acquaintances',
 'acquainted',
 'acquire',
 'acquired',
 'acquit',
 'acronym',
 'across',
 'act',
 'actauly',
 'acted',
 'acting',
 'action',
 'actions',
 'activations',
 'active',
 'actively',
 'activism',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'actresses',
 'acts',
 'actual',
 'actuality',
 'actually',
 'acuity',
 'acumen',
 'acute',
 'acutely',
 'ad',
 'adam',
 'adams',
 'adapt',
 'adapted',
 'adaption',
 'add',
 'added',
 'addict',
 'addicted',
 'addiction',
 'addictive',
 'adding',
 'addison',
 'addisons',
 'addition',
 'additional',
 'additionally',
 'addled',
 'address',
 'addressed',
 'addressing',
 'adds',
 'ade',
 'adequate',
 'adequately',
 'adf',
 'adhere',
 'adherence',
 'adjectival',
 'adjectives',
 'adjoining',
 'adjust',
 'adjusting',
 'adjustment',
 'adjustments',
 'admin',
 'administration',
 'administrator',
 'administrators',
 'admiral',
 'admiration',
 'admire',
 'admired',
 'admires',
 'admiring',
 'admission',
 'admissions',
 'admit',
 'admits',
 'admittance',
 'admitted',
 'admittedly',
 'admitting',
 'adn',
 'adolescence',
 'adomen',
 'adopt',
 'adopted',
 'adopting',
 'adoption',
 'adorable',
 'adoration',
 'adore',
 'adored',
 'adores',
 'adoring',
 'adorns',
 'adrasteius',
 'adrenaline',
 'adress',
 'adrian',
 'adrift',
 'ads',
 'adsense',
 'adult',
 'adulth',
 'adulthood',
 'adults',
 'advance',
 'advanced',
 'advancement',
 'advances',
 'advantage',
 'advent',
 'adventure',
 'adventures',
 'adventurous',
 'adversary',
 'adverse',
 'adversely',
 'advertised',
 'advertisement',
 'advertisements',
 'advertises',
 'advertising',
 'advertorial',
 'adverts',
 'advice',
 'advil',
 'advise',
 'advisers',
 'advocacy',
 'advocate',
 'advocates',
 'advocating',
 'aesthetic',
 'aesthetics',
 'af',
 'afaerytaleinmakebelieve',
 'afar',
 'aff',
 'affair',
 'affairs',
 'affeccion',
 'affect',
 'affected',
 'affecti',
 'affecting',
 'affection',
 'affectionate',
 'affectionately',
 'affections',
 'affects',
 'affend',
 'affiliate',
 'affirm',
 'affirmation',
 'affirmations',
 'affirmative',
 'affirmed',
 'afford',
 'affordable',
 'affords',
 'affron',
 'affronted',
 'afghan',
 'aficionado',
 'afield',
 'aforementioned',
 'afp',
 'afrad',
 'afrade',
 'afraid',
 'africa',
 'african',
 'africans',
 'after',
 'aftereffects',
 'aftermath',
 'afternoon',
 'afternoons',
 'afterward',
 'afterwards',
 'ag',
 'aga',
 'agai',
 'again',
 'against',
 'agape',
 'age',
 'aged',
 'ageing',
 'agencies',
 'agenda',
 'agent',
 'ages',
 'aggie',
 'aggrandisement',
 'aggravated',
 'aggravating',
 'aggression',
 'aggressive',
 'aggressiven',
 'agi',
 'agiatated',
 'agility',
 'aging',
 'agitat',
 'agitated',
 'agn',
 'agnes',
 'agnostics',
 'ago',
 'agonised',
 'agonising',
 'agonized',
 'agony',
 'agoraphobic',
 'agree',
 'agreed',
 'agreeing',
 'agreement',
 'agtalk',
 'ah',
 'ahaha',
 'ahahahaha',
 'ahead',
 'ahem',
 'ahhh',
 'ahkman',
 'ahmed',
 'ai',
 'aid',
 'aided',
 'aids',
 'aiiiiighhhht',
 'ailments',
 'aim',
 'aimed',
 'aiming',
 'aimless',
 'aimlessly',
 'aims',
 'ain',
 'aint',
 'air',
 'airbrushing',
 'airbus',
 'aircleaner',
 'aircraft',
 'airlin',
 'airline',
 'airplane',
 'airport',
 'airports',
 'airritated',
 'airtime',
 'aisl',
 'aisles',
 'aiw',
 'aj',
 'ajahn',
 'ajmed',
 'aka',
 'akin',
 'akron',
 'akshay',
 'aku',
 'akward',
 'al',
 'ala',
 'alabama',
 'alain',
 'alan',
 'alarm',
 'alarmed',
 'alarming',
 'alaska',
 'alba',
 'albeit',
 'albert',
 'albino',
 'album',
 'albums',
 'albuquerque',
 'alcest',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alcove',
 'ald',
 'aldridge',
 'alec',
 'alene',
 'alert',
 'alertness',
 'alex',
 'alexa',
 'alexander',
 'alexandra',
 'alexei',
 'alexis',
 'alfed',
 'alfie',
 'alfred',
 'algebra',
 'algorithmic',
 'alhamdulillah',
 'ali',
 'alibi',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alight',
 'align',
 'aligncenter',
 'alignment',
 'alise',
 'alittle',
 'alive',
 'all',
 'allah',
 'allan',
 'allegation',
 'alleging',
 'allen',
 'allergen',
 'allergic',
 'allergies',
 'allergy',
 'alleviate',
 'alley',
 'alleys',
 'alli',
 'alliance',
 'allies',
 'alll',
 'allocated',
 'allotted',
 'allow',
 'allowable',
 'allowances',
 'allowed',
 'allowfullscreen',
 'allowing',
 'allows',
 'alls',
 'allthingsbucks',
 'allusion',
 'ally',
 'almond',
 'almost',
 'aloft',
 'alon',
 'alone',
 'along',
 'alonger',
 'alongside',
 'aloof',
 'alot',
 'alotta',
 'alphabet',
 'alre',
 'already',
 'alright',
 'also',
 'alsways',
 'alt',
 'altar',
 'alteration',
 'alterations',
 'altered',
 'altering',
 'alternate',
 'alternated',
 'alternating',
 'alternative',
 'alternatives',
 'although',
 'altitudes',
 'altogether',
 'alton',
 'aluminum',
 'alumninium',
 'alva',
 'alway',
 'always',
 'am',
 'ama',
 'amalgamation',
 'amateurs',
 'amazed',
 'amazement',
 'amazing',
 'amazingly',
 'amazingness',
 'amazon',
 'ambassador',
 'amber',
 'ambience',
 'ambient',
 'ambition',
 'ambitious',
 'ambleside',
 'ambulance',
 'ambulatory',
 'ambushed',
 'amd',
 'amendment',
 'amenities',
 'america',
 'american',
 'americana',
 'americans',
 'americas',
 'amid',
 'amidst',
 'amish',
 'amisha',
 'amiss',
 'amits',
 'amkris',
 'amma',
 'amman',
 'among',
 'amongst',
 'amorous',
 'amorphous',
 'amos',
 'amount',
 'amounting',
 'amounts',
 'amp',
 'amparo',
 'ampatuan',
 'amped',
 'amphetamine',
 'ample',
 'amplified',
 'amplifies',
 'amsterdam',
 'amud',
 'amus',
 'amused',
 'amusem',
 'amusement',
 'amusing',
 'amvassago',
 'amy',
 'an',
 'ana',
 'anaestheti',
 'anaesthetic',
 'anal',
 'analogy',
 'analyse',
 'analyses',
 'analysing',
 'analysis',
 'analyze',
 'analyzed',
 'analyzing',
 'anansi',
 'anatomy',
 'ancestral',
 'anchorage',
 'ancient',
 'ancients',
 'and',
 'andangry',
 'andare',
 'anderson',
 'andintrupte',
 'andover',
 'andrea',
 'andreas',
 'andrew',
 'andri',
 'andrus',
 'andthenwear',
 'andy',
 'anesthetized',
 'ang',
 'angalo',
 'angee',
 'angel',
 'angeles',
 'angelic',
 'angels',
 'anger',
 'angered',
 'angie',
 'angle',
 'angled',
 'angles',
 'angry',
 'angst',
 'angsty',
 'anguis',
 'anguish',
 'anguished',
 'anha',
 'anim',
 'animal',
 'animals',
 'animate',
 'animated',
 'animators',
 'anime',
 'animesh',
 'animosity',
 'anipike',
 'ankle',
 'ankles',
 'anklets',
 'ann',
 'anna',
 'annabel',
 'anne',
 'annie',
 'anniversary',
 'annotating',
 'annotation',
 'announce',
 'announced',
 'announcement',
 'announcements',
 'announcing',
 'annoy',
 'annoya',
 'annoyance',
 'annoyed',
 'annoying',
 'annoyingly',
 'annual',
 'annuals',
 'annulled',
 'annulment',
 'annus',
 'ano',
 'anon',
 'anonymity',
 'anonymous',
 'anotehr',
 'another',
 'anothers',
 'ansi',
 'answer',
 'answered',
 'answering',
 'answers',
 'antagonism',
 'anthem',
 'anthology',
 'anthony',
 'anti',
 'anticipated',
 'anticipating',
 'anticipation',
 'antics',
 'antidepressants',
 'antidote',
 'antipasti',
 'antique',
 'antiquities',
 'antisocial',
 'antivirus',
 'antm',
 'antoinette',
 'antonio',
 'antonios',
 'ants',
 'antsy',
 'anxieties',
 'anxiety',
 'anxio',
 'anxious',
 'anxiously',
 'any',
 'anybody',
 'anyhow',
 'anymmore',
 'anymore',
 'anyone',
 'anyones',
 'anything',
 'anythings',
 'anyway',
 'anyways',
 'anywhere',
 'aoa',
 'aoi',
 'aol',
 'aoshi',
 'aout',
 'ap',
 'apa',
 'apart',
 'apartment',
 'apartments',
 'apathetic',
 'apathy',
 'apawa',
 'apaya',
 'apc',
 'apendages',
 'apgujeong',
 'aplin',
 'apo',
 'apocalypses',
 'apologetic',
 'apologies',
 'apologise',
 'apologize',
 'apologizes',
 'apologizing',
 'apology',
 'apoplectic',
 'apostrophe',
 'apothecaries',
 'apothecary',
 'app',
 'appalled',
 'apparent',
 'apparently',
 'appeal',
 'appealing',
 'appeals',
 'appear',
 'appearanc',
 'appearance',
 'appearances',
 'appeared',
 'appearing',
 'appears',
 'appease',
 'appeased',
 'appetite',
 'applainces',
 'applause',
 'apple',
 'applebees',
 'apples',
 'application',
 'applications',
 'applied',
 'apply',
 'applying',
 'appointed',
 'appointment',
 'appointments',
 'apprecia',
 'appreciate',
 'appreciated',
 'appreciates',
 'appreciation',
 'appreciative',
 'apprehension',
 'apprehensive',
 'appriciation',
 'apprised',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'appropriate',
 'appropriately',
 'approval',
 'approve',
 'approx',
 'approximate',
 'approximately',
 'apps',
 'appts',
 'apraxia',
 'april',
 'apron',
 'apt',
 'ar',
 'arab',
 'arabia',
 'arabs',
 'araminta',
 'arc',
 'arca',
 'arcade',
 'archbishop',
 'archdiocese',
 'arched',
 'archeological',
 'arches',
 'architects',
 'architectural',
 'architecturally',
 'ardmore',
 'are',
 'area',
 'areas',
 'aren',
 'arena',
 'arent',
 'aretha',
 'arguably',
 'argue',
 'argued',
 'arguing',
 'argume',
 'argument',
 'arguments',
 'ari',
 'arialblue',
 'ariel',
 'arise',
 'arist',
 'aristophanes',
 'arlovski',
 'arm',
 'armani',
 'armed',
 'armenian',
 'armistice',
 'armor',
 'armoury',
 'armpits',
 'arms',
 'army',
 'arnold',
 'aroma',
 'arose',
 'arou',
 'around',
 'arouse',
 'aroused',
 'arousing',
 'arrange',
 'arranged',
 'arrangement',
 'arrangements',
 'arrangment',
 'array',
 'arrested',
 'arrises',
 'arriva',
 'arrival',
 'arrivals',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogance',
 'arrogant',
 'arrow',
 'ars',
 'arse',
 'arsenal',
 'art',
 'artefacts',
 'article',
 'articles',
 'articulacy',
 'articulate',
 'articulated',
 'articulating',
 'artifically',
 'artificial',
 'artificially',
 'artillery',
 'artisan',
 'artisans',
 'artist',
 'artistic',
 'artistry',
 'artists',
 'arts',
 'artwork',
 'arty',
 'arugh',
 'arun',
 'arvo',
 'aryans',
 'aryiku',
 'as',
 'asa',
 'asami',
 'asasoulawakens',
 'asbestos',
 'ascension',
 'asciatic',
 'asd',
 'ash',
 'ashame',
 'ashamed',
 'ashers',
 'ashes',
 'ashi',
 'ashley',
 'ashlotte',
 ...]